name: Validate Pull Request

on: pull_request

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17.0.7
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set Docker Host env variable
        run: echo "DOCKER_HOST=$(docker context ls --format '{{print .DockerEndpoint}}' | tr -d '\n')" >> $GITHUB_ENV
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          ./gradlew clean build --stacktrace --scan --console=plain --no-daemon
          ./gradlew codeCoverageReport --console=plain --no-daemon
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
